# Generated by Django 5.2.3 on 2025-06-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('datos_rurales', models.TextField(blank=True)),
                ('datos_geograficos', models.TextField(blank=True)),
                ('datos_climaticos', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
