# Generated by Django 5.2.3 on 2025-06-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punto',
            name='datos_climaticos',
        ),
        migrations.RemoveField(
            model_name='punto',
            name='datos_geograficos',
        ),
        migrations.RemoveField(
            model_name='punto',
            name='datos_rurales',
        ),
        migrations.RemoveField(
            model_name='punto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='punto',
            name='cambios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='punto',
            name='cultivos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='punto',
            name='humedad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='punto',
            name='temperatura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='punto',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='punto',
            name='viento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='punto',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/')),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api.punto')),
            ],
        ),
    ]
